import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import { Header } from "@/components/Header";
import { CartDrawer } from "@/components/CartDrawer";
import { TopProgressBar } from "@/components/TopProgressBar";
import { BottomNav } from "@/components/BottomNav";
import { Footer } from "@/components/Footer";
import { ChatBot } from "@/components/ChatBot";
import { BackendWarmup } from "@/components/BackendWarmup";
import { StructuredData } from "@/components/StructuredData";
import { CommunityPopup } from "@/components/CommunityPopup";

// Inter is served by next/font (self-hosted at build time) — no Google Fonts CDN request.
// display:swap ensures text is visible immediately while the font loads (avoids invisible text).
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: {
    default: "PriceBasket — Compare Blinkit, Zepto & BigBasket Prices | Save ₹500/Month",
    template: "%s | PriceBasket",
  },
  description:
    "Compare Blinkit, Zepto, Swiggy Instamart, BigBasket & JioMart grocery prices in real-time. Find the cheapest quick-commerce app & save ₹500/month. Free, no app needed.",
  verification: {
    google: process.env.NEXT_PUBLIC_GSC_VERIFICATION ?? undefined,
  },
  keywords: [
    "blinkit vs zepto price comparison",
    "cheapest grocery app india",
    "grocery price comparison india",
    "blinkit zepto bigbasket price compare",
    "swiggy instamart vs blinkit",
    "quick commerce price comparison",
    "online grocery deals india",
    "save money groceries india",
    "grocery price tracker india",
    "blinkit price check",
    "zepto price check",
    "bigbasket vs blinkit",
    "zepto vs swiggy instamart",
    "grocery delivery price comparison",
    "pricebasket india",
    "grocery price comparison mumbai",
    "grocery price comparison delhi",
    "grocery price comparison bangalore",
    "cheapest grocery delivery india",
    "grocery price alert india",
  ],
  metadataBase: new URL("https://pricebasket.in"),
  openGraph: {
    title: "PriceBasket — Compare Prices Across 10 Platforms",
    description: "Real-time price comparison across Blinkit, Zepto, BigBasket, Instamart & more. Save money on every order.",
    url: "https://pricebasket.in",
    siteName: "Price Basket",
    type: "website",
    locale: "en_IN",
    // OG image is auto-generated by app/opengraph-image.tsx (Next injects the URL).
  },
  twitter: {
    card: "summary_large_image",
    title: "PriceBasket — Compare Prices Across 10 Platforms",
    description: "Real-time price comparison across Blinkit, Zepto, BigBasket & more.",
    // Twitter image is auto-generated by app/twitter-image.tsx.
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: "/icon.svg",
  },
  alternates: {
    canonical: "https://pricebasket.in",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#ea580c",
};

const GA_ID = process.env.NEXT_PUBLIC_GA_ID;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        {/*
          ── Preconnect only to origins we actually request ──────────────────
          fonts.googleapis.com / fonts.gstatic.com are NOT needed: Inter is
          self-hosted by next/font at build time, so no Google Fonts CDN call
          is ever made. Keeping those hints wastes a TCP+TLS handshake and
          triggers the Lighthouse "Unused preconnect" warning.

          googletagmanager.com IS used (GA4 script below), so we keep that.
          cdn.grofers.com / cdn.blinkit.com serve most product images — a
          preconnect here shaves ~100 ms off the first image request.
        */}
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://cdn.grofers.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://cdn.blinkit.com" crossOrigin="anonymous" />
        {/* dns-prefetch as a fallback for browsers that ignore preconnect */}
        <link rel="dns-prefetch" href="https://api.pricebasket.in" />
        <link rel="dns-prefetch" href="https://cdn.zeptonow.com" />
      </head>
      {/*
        ── Google Analytics 4 ──────────────────────────────────────────────
        strategy="lazyOnload" defers the 142 KB gtag bundle until the page
        is fully idle — removes it from the critical path and saves ~63 KiB
        of unused JS during initial load (Lighthouse "Reduce unused JS" fix).
      */}
      {GA_ID && (
        <>
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
            strategy="lazyOnload"
          />
          <Script id="ga4-init" strategy="lazyOnload">{`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_ID}', {
              page_path: window.location.pathname,
              send_page_view: true,
            });
          `}</Script>
        </>
      )}
      <body>
        <StructuredData />
        <Providers>
          <BackendWarmup />
          <TopProgressBar />
          <Header />
          {/* pb-[58px] on mobile reserves space for the fixed BottomNav */}
          <main className="min-h-[calc(100vh-56px)] pb-[58px] md:pb-0">{children}</main>
          <Footer />
          <BottomNav />
          <CartDrawer />
          <ChatBot />
          <CommunityPopup />
          <Toaster
            position="top-center"
            containerStyle={{ zIndex: 999999 }}
            toastOptions={{
              duration: 3500,
              style: {
                borderRadius: "12px",
                fontFamily: "var(--font-inter)",
                fontSize: "14px",
                fontWeight: "500",
                boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
              },
              success: {
                iconTheme: { primary: "#ea580c", secondary: "#fff" },
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
