import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import { Header } from "@/components/Header";
import { CartDrawer } from "@/components/CartDrawer";
import { TopProgressBar } from "@/components/TopProgressBar";
import { BottomNav } from "@/components/BottomNav";
import { Footer } from "@/components/Footer";
import { ChatBot } from "@/components/ChatBot";
import { BackendWarmup } from "@/components/BackendWarmup";
import { StructuredData } from "@/components/StructuredData";
import { CommunityPopup } from "@/components/CommunityPopup";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: {
    default: "PriceBasket — Compare Blinkit, Zepto & BigBasket Prices | Save ₹500/Month",
    template: "%s | PriceBasket",
  },
  description:
    "Compare Blinkit, Zepto, Swiggy Instamart, BigBasket & JioMart grocery prices in real-time. Find the cheapest quick-commerce app & save ₹500/month. Free, no app needed.",
  verification: {
    google: process.env.NEXT_PUBLIC_GSC_VERIFICATION ?? undefined,
  },
  keywords: [
    "blinkit vs zepto price comparison",
    "cheapest grocery app india",
    "grocery price comparison india",
    "blinkit zepto bigbasket price compare",
    "swiggy instamart vs blinkit",
    "quick commerce price comparison",
    "online grocery deals india",
    "save money groceries india",
    "grocery price tracker india",
    "blinkit price check",
    "zepto price check",
    "bigbasket vs blinkit",
    "zepto vs swiggy instamart",
    "grocery delivery price comparison",
    "pricebasket india",
    "grocery price comparison mumbai",
    "grocery price comparison delhi",
    "grocery price comparison bangalore",
    "cheapest grocery delivery india",
    "grocery price alert india",
  ],
  metadataBase: new URL("https://pricebasket.in"),
  openGraph: {
    title: "Price Basket — Compare Prices Across 10 Platforms",
    description: "Real-time price comparison across Blinkit, Zepto, BigBasket, Instamart & more. Save money on every order.",
    url: "https://pricebasket.in",
    siteName: "Price Basket",
    type: "website",
    locale: "en_IN",
    // OG image is auto-generated by app/opengraph-image.tsx (Next injects the URL).
  },
  twitter: {
    card: "summary_large_image",
    title: "Price Basket — Compare Prices Across 10 Platforms",
    description: "Real-time price comparison across Blinkit, Zepto, BigBasket & more.",
    // Twitter image is auto-generated by app/twitter-image.tsx.
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: "/icon.svg",
  },
  alternates: {
    canonical: "https://pricebasket.in",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#ea580c",
};

const GA_ID = process.env.NEXT_PUBLIC_GA_ID;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        {/* Preconnect to speed up third-party resources — reduces mobile LCP */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://api.pricebasket.in" />
      </head>
      {/* ── Google Analytics 4 ── */}
      {GA_ID && (
        <>
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
            strategy="afterInteractive"
          />
          <Script id="ga4-init" strategy="afterInteractive">{`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_ID}', {
              page_path: window.location.pathname,
              send_page_view: true,
            });
          `}</Script>
        </>
      )}
      <body>
        <StructuredData />
        <Providers>
          <BackendWarmup />
          <TopProgressBar />
          <Header />
          {/* pb-[58px] on mobile reserves space for the fixed BottomNav */}
          <main className="min-h-[calc(100vh-56px)] pb-[58px] md:pb-0">{children}</main>
          <Footer />
          <BottomNav />
          <CartDrawer />
          <ChatBot />
          <CommunityPopup />
          <Toaster
            position="top-center"
            containerStyle={{ zIndex: 999999 }}
            toastOptions={{
              duration: 3500,
              style: {
                borderRadius: "12px",
                fontFamily: "var(--font-inter)",
                fontSize: "14px",
                fontWeight: "500",
                boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
              },
              success: {
                iconTheme: { primary: "#ea580c", secondary: "#fff" },
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
