"""
Product catalog: category hierarchy + master query list.
Imported by bulk_product_scraper.py and the Celery task.
"""
from typing import Dict, List

# ─────────────────────────────────────────────────────────────────────────────
# Category Hierarchy
# ─────────────────────────────────────────────────────────────────────────────
CATEGORY_HIERARCHY: Dict[str, dict] = {
    "fruits-vegetables": {
        "name": "Fruits & Vegetables",
        "icon": "🥦",
        "display_order": 1,
    },
    "dairy-breakfast": {
        "name": "Dairy & Breakfast",
        "icon": "🥛",
        "display_order": 2,
    },
    "snacks-drinks": {
        "name": "Snacks & Drinks",
        "icon": "🍿",
        "display_order": 3,
    },
    "atta-rice-dal": {
        "name": "Atta, Rice & Dal",
        "icon": "🌾",
        "display_order": 4,
    },
    "oils-spices": {
        "name": "Oils & Spices",
        "icon": "🫙",
        "display_order": 5,
    },
    "bakery-biscuits": {
        "name": "Bakery & Biscuits",
        "icon": "🍞",
        "display_order": 6,
    },
    "personal-care": {
        "name": "Personal Care",
        "icon": "🧴",
        "display_order": 7,
    },
    "household": {
        "name": "Household Essentials",
        "icon": "🧹",
        "display_order": 8,
    },
    "chicken-meat": {
        "name": "Chicken & Meat",
        "icon": "🍗",
        "display_order": 9,
    },
    "frozen-foods": {
        "name": "Frozen Foods",
        "icon": "🧊",
        "display_order": 10,
    },
    "beauty-cosmetics": {
        "name": "Beauty & Cosmetics",
        "icon": "💄",
        "display_order": 11,
    },
    "baby-care": {
        "name": "Baby Care",
        "icon": "👶",
        "display_order": 12,
    },
    "pet-care": {
        "name": "Pet Care",
        "icon": "🐾",
        "display_order": 13,
    },
    "electronics": {
        "name": "Electronics & Accessories",
        "icon": "📱",
        "display_order": 14,
    },
    "kitchen-essentials": {
        "name": "Kitchen Essentials",
        "icon": "🍳",
        "display_order": 15,
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# Master product query list — 300+ queries across all categories
# Each query is sent to every enabled platform scraper
# ─────────────────────────────────────────────────────────────────────────────
PRODUCT_QUERIES: Dict[str, List[str]] = {
    "fruits-vegetables": [
        "Fresh Tomato 1kg", "Fresh Onion 1kg", "Fresh Potato 1kg", "Fresh Spinach 250g",
        "Fresh Banana 1 dozen", "Fresh Apple 4 pcs", "Fresh Lemon 6 pcs", "Fresh Ginger 100g",
        "Fresh Garlic 100g", "Fresh Green Chilli 100g", "Fresh Coriander 100g", "Fresh Carrot 500g",
        "Fresh Capsicum 3 pcs", "Fresh Cucumber 3 pcs", "Fresh Brinjal 500g", "Fresh Cauliflower",
        "Fresh Cabbage", "Fresh Peas 500g", "Fresh Beans 250g", "Fresh Bitter Gourd 500g",
        "Fresh Pumpkin 500g", "Fresh Sweet Potato 500g", "Fresh Beetroot 500g",
        "Fresh Mango 1kg", "Fresh Papaya", "Fresh Watermelon", "Fresh Grapes 500g",
        "Fresh Pomegranate", "Fresh Pineapple", "Fresh Guava 500g", "Fresh Strawberry 200g",
        "Fresh Mushroom 200g", "Fresh Broccoli", "Fresh Avocado", "Fresh Kiwi",
        "Fresh Sweet Corn", "Fresh Drumstick 250g", "Fresh Radish 500g", "Fresh Okra 250g",
        "Fresh Curry Leaves 50g", "Fresh Mint 50g", "Fresh Fenugreek 100g",
        "Fresh Jackfruit 500g", "Fresh Coconut", "Fresh Tender Coconut",
        "Cherry Tomato 250g", "Baby Spinach 100g", "Iceberg Lettuce",
    ],
    "dairy-breakfast": [
        "Amul Gold Milk 1L", "Amul Taaza Milk 500ml", "Mother Dairy Milk 1L",
        "Amul Butter 500g", "Amul Butter 100g", "Britannia Butter 100g",
        "Amul Paneer 200g", "Mother Dairy Paneer 200g", "Milky Mist Paneer 200g",
        "Amul Cheese Slices 200g", "Britannia Cheese Slices 200g", "Go Cheese Slices 200g",
        "Amul Curd 400g", "Mother Dairy Curd 400g", "Nestle Actiplus Curd 400g",
        "Amul Ghee 500ml", "Mother Dairy Ghee 500ml", "Patanjali Ghee 500ml",
        "Amul Cream 200ml", "Amul Mozzarella Cheese 200g",
        "Britannia Whole Wheat Bread 400g", "Harvest Gold Bread 400g", "Modern Bread 400g",
        "Kelloggs Corn Flakes 500g", "Quaker Oats 500g", "Bagrry's Oats 500g",
        "Saffola Oats 500g", "Kelloggs Chocos 500g", "Nestle Milo 400g",
        "Amul Lactose Free Milk 250ml", "Epigamia Greek Yogurt 90g",
        "Farm Fresh Eggs 6 pcs", "Eggoz Eggs 6 pcs",
        "Amul Shrikhand 100g", "Amul Lassi 200ml", "Mother Dairy Lassi 200ml",
        "Amul Buttermilk 200ml", "Britannia Cheese Spread 180g",
        "Kelloggs Muesli 500g", "Quaker Oats Masala 39g",
    ],
    "snacks-drinks": [
        "Lays Classic Salted 26g", "Lays Magic Masala 26g", "Kurkure Masala Munch 90g",
        "Haldirams Aloo Bhujia 200g", "Haldirams Moong Dal 200g", "Bingo Mad Angles 90g",
        "Pringles Original 107g", "Doritos Nacho Cheese 123g",
        "Parle G Biscuits 800g", "Britannia Good Day 200g", "Oreo Biscuits 120g",
        "Bourbon Biscuits 200g", "Sunfeast Dark Fantasy 300g",
        "Cadbury Dairy Milk 50g", "Cadbury 5 Star 40g", "KitKat 4 Finger 41.5g",
        "Snickers 50g", "Ferrero Rocher 3 pcs", "Cadbury Celebrations 118g",
        "Coca Cola 750ml", "Pepsi 750ml", "Sprite 750ml", "Thums Up 750ml",
        "Tropicana Orange Juice 1L", "Real Fruit Juice 1L", "Minute Maid 1L",
        "Red Bull Energy Drink 250ml", "Monster Energy 500ml", "Sting Energy 250ml",
        "Bisleri Water 1L", "Kinley Water 1L", "Aquafina Water 1L",
        "Maggi Noodles 70g", "Yippee Noodles 70g", "Top Ramen Noodles 70g",
        "Cornitos Nachos 150g", "Too Yumm Veggie Sticks 54g", "Bikaji Bhujia 200g",
        "Roasted Almonds 100g", "Cashews 100g", "Mixed Dry Fruits 200g",
        "Raisins 100g", "Pistachios 100g", "Walnuts 100g", "Dates 250g",
        "Nescafe Classic 50g", "Bru Coffee 50g", "Tata Tea Premium 250g",
        "Lipton Green Tea 25 bags", "Tetley Green Tea 25 bags", "Taj Mahal Tea 250g",
        "Parle Monaco Biscuits 200g", "Britannia NutriChoice 200g",
        "Sunfeast Marie Light 200g", "Britannia Marie Gold 200g",
        "Haldirams Bhujia 200g", "Haldirams Mixture 200g",
        "Coca Cola 2L", "Pepsi 2L", "Sprite 2L",
        "Tropicana Apple Juice 1L", "Real Mixed Fruit Juice 1L",
    ],
    "atta-rice-dal": [
        "Aashirvaad Atta 5kg", "Aashirvaad Atta 10kg", "Pillsbury Atta 5kg",
        "Patanjali Atta 5kg", "Fortune Atta 5kg", "Shaktibhog Atta 5kg",
        "India Gate Basmati Rice 5kg", "Daawat Basmati Rice 5kg", "Kohinoor Basmati Rice 5kg",
        "Fortune Sona Masoori Rice 5kg", "Aashirvaad Select Sharbati Atta 5kg",
        "Tata Sampann Toor Dal 1kg", "Tata Sampann Chana Dal 1kg", "Tata Sampann Moong Dal 1kg",
        "Tata Sampann Masoor Dal 1kg", "Tata Sampann Urad Dal 1kg",
        "Patanjali Toor Dal 1kg", "Patanjali Chana Dal 1kg",
        "Tata Sugar 1kg", "Patanjali Sugar 1kg",
        "Tata Salt 1kg", "Catch Salt 1kg", "Patanjali Salt 1kg",
        "Saffola Poha 500g", "MTR Poha 500g",
        "Rajdhani Besan 500g", "Patanjali Besan 500g", "Tata Sampann Besan 500g",
        "Quaker Oats 1kg", "Saffola Oats 1kg",
        "India Gate Feast Rozzana Rice 5kg", "Daawat Rozana Basmati 5kg",
        "Fortune Chakki Fresh Atta 10kg", "Aashirvaad Multigrain Atta 5kg",
        "Tata Sampann Rajma 500g", "Tata Sampann Kabuli Chana 500g",
        "Patanjali Rajma 500g", "Patanjali Kabuli Chana 500g",
        "Kohinoor Super Value Basmati Rice 1kg", "India Gate Classic Basmati 1kg",
    ],
    "oils-spices": [
        "Fortune Sunflower Oil 1L", "Saffola Gold Oil 1L", "Dhara Sunflower Oil 1L",
        "Fortune Mustard Oil 1L", "Patanjali Mustard Oil 1L",
        "Figaro Olive Oil 500ml", "Borges Olive Oil 500ml", "DiSano Olive Oil 500ml",
        "Everest Garam Masala 100g", "MDH Garam Masala 100g", "Catch Garam Masala 100g",
        "Everest Chilli Powder 100g", "MDH Chilli Powder 100g",
        "Everest Turmeric Powder 100g", "MDH Turmeric 100g", "Patanjali Turmeric 100g",
        "Everest Coriander Powder 100g", "MDH Coriander Powder 100g",
        "Maggi Tomato Ketchup 500g", "Kissan Tomato Ketchup 500g", "Heinz Tomato Ketchup 500g",
        "Maggi Hot Sweet Sauce 400g", "Ching's Schezwan Sauce 250g",
        "Patanjali Honey 500g", "Dabur Honey 500g", "Apis Honey 500g",
        "Kissan Mixed Fruit Jam 500g",
        "Fortune Groundnut Oil 1L", "Saffola Active Oil 1L", "Fortune Rice Bran Oil 1L",
        "Everest Pav Bhaji Masala 100g", "MDH Pav Bhaji Masala 100g",
        "Everest Biryani Masala 50g", "MDH Biryani Masala 50g",
        "Everest Rajma Masala 100g", "MDH Dal Makhani Masala 100g",
        "Maggi Masala 80g", "Ching's Hakka Noodles Masala 20g",
        "Catch Pepper Powder 100g", "Everest Cumin Powder 100g",
    ],
    "bakery-biscuits": [
        "Britannia Cake 60g", "English Oven Cake 400g",
        "Parle Monaco Biscuits 200g", "Parle Krackjack 200g",
        "Sunfeast Marie Light 200g", "Parle Marie 200g", "Britannia Marie Gold 200g",
        "Britannia Rusk 200g", "Parle Rusk 200g", "Modern Rusk 200g",
        "Britannia Treat Jam Rolls 100g", "Parle Melody 100g",
        "Cadbury Choco Fills 75g", "Sunfeast Bounce 75g",
        "Britannia Good Day Cashew 200g", "Parle Hide and Seek 200g",
        "Sunfeast Dark Fantasy Choco Fills 300g", "Oreo Double Stuff 120g",
        "Britannia Tiger Biscuits 200g", "Parle Glucose Biscuits 200g",
        "Britannia Nutrichoice Digestive 400g", "McVities Digestive Biscuits 250g",
    ],
    "personal-care": [
        "Dove Shampoo 180ml", "Head Shoulders Shampoo 180ml", "Pantene Shampoo 180ml",
        "TRESemme Shampoo 200ml", "Sunsilk Shampoo 180ml", "Clinic Plus Shampoo 175ml",
        "Dove Soap 100g", "Lux Soap 100g", "Dettol Soap 75g", "Lifebuoy Soap 100g",
        "Pears Soap 75g", "Santoor Soap 100g", "Himalaya Neem Soap 75g",
        "Colgate Total Toothpaste 150g", "Colgate MaxFresh 150g", "Pepsodent Toothpaste 150g",
        "Sensodyne Toothpaste 70g", "Dabur Red Toothpaste 200g", "Patanjali Dant Kanti 200g",
        "Nivea Face Wash 100ml", "Himalaya Face Wash 100ml", "Garnier Face Wash 100ml",
        "Pond's Face Wash 100ml",
        "Dove Body Lotion 250ml", "Nivea Body Lotion 200ml", "Vaseline Body Lotion 200ml",
        "Parachute Coconut Oil 200ml", "Dabur Vatika Hair Oil 200ml", "Bajaj Almond Oil 200ml",
        "Axe Deodorant 150ml", "Fogg Deodorant 150ml", "Wild Stone Deodorant 150ml",
        "Whisper Ultra Pads 7 pcs", "Stayfree Secure 7 pcs", "Sofy Bodyfit 7 pcs",
        "Gillette Mach3 Razor", "Veet Hair Removal Cream 50g",
        "Dove Conditioner 180ml", "Pantene Conditioner 180ml",
        "Colgate Toothbrush Medium", "Oral B Toothbrush Medium",
        "Listerine Mouthwash 250ml", "Colgate Mouthwash 250ml",
        "Dettol Handwash 200ml", "Lifebuoy Handwash 200ml", "Savlon Handwash 200ml",
        "Himalaya Moisturizer 100ml", "Nivea Moisturizer 100ml",
        "Garnier Sunscreen SPF 50 50ml", "Lotus Sunscreen SPF 40 100ml",
        "Parachute Advansed Body Lotion 400ml",
        "Dove Men Care Shampoo 180ml", "Garnier Men Face Wash 100ml",
    ],
    "household": [
        "Surf Excel Detergent 1kg", "Ariel Detergent 1kg", "Tide Detergent 1kg",
        "Rin Detergent 1kg", "Wheel Detergent 1kg", "Patanjali Detergent 1kg",
        "Vim Dishwash Bar 200g", "Pril Dishwash Liquid 500ml", "Exo Dishwash Bar 200g",
        "Harpic Power Plus 500ml", "Domex Toilet Cleaner 500ml", "Lizol Floor Cleaner 500ml",
        "Colin Glass Cleaner 500ml", "Dettol Disinfectant Liquid 500ml",
        "Odonil Air Freshener 50g", "Ambi Pur Air Freshener 275ml",
        "Good Knight Mosquito Coil", "All Out Mosquito Repellent", "Mortein Spray 425ml",
        "Scotch Brite Scrub Pad 3 pcs", "Scotch Brite Sponge Wipe",
        "Garbage Bags 30 pcs", "Cling Wrap 30m", "Aluminium Foil 9m",
        "Comfort Fabric Conditioner 800ml", "Ezee Liquid Detergent 500ml",
        "Surf Excel Matic Liquid 1L", "Ariel Matic Liquid 1L",
        "Harpic Bathroom Cleaner 500ml", "Lizol Disinfectant 500ml",
        "Scotch Brite Dish Cloth 2 pcs",
        "Zip Lock Bags 30 pcs",
        "Dettol Surface Cleaner 500ml", "Savlon Surface Disinfectant 500ml",
    ],
    "chicken-meat": [
        "Fresh Chicken Curry Cut 500g", "Fresh Chicken Breast 500g", "Fresh Chicken Whole 1kg",
        "Fresh Mutton Curry Cut 500g", "Fresh Fish Rohu 500g", "Fresh Prawns 250g",
        "Licious Chicken Keema 500g", "Licious Chicken Boneless 500g",
        "Zappfresh Chicken 500g", "Suguna Chicken 500g",
        "Fresh Chicken Drumsticks 500g", "Fresh Chicken Wings 500g",
        "Licious Mutton Keema 500g", "Licious Fish Fillet 250g",
        "Venky's Chicken Sausages 200g", "Godrej Yummiez Chicken Nuggets 400g",
    ],
    "frozen-foods": [
        "McCain French Fries 420g", "McCain Smiles 415g", "McCain Aloo Tikki 400g",
        "Amul Ice Cream Vanilla 1L", "Kwality Walls Ice Cream 700ml",
        "Haldirams Frozen Samosa 400g", "ITC Master Chef Frozen Paratha 400g",
        "Godrej Yummiez Chicken Nuggets 400g", "Venky's Chicken Nuggets 400g",
        "Frozen Mixed Vegetables 500g", "Frozen Green Peas 500g",
        "McCain Burger Patty 400g",
        "Kwality Walls Cornetto Ice Cream", "Amul Chocobar Ice Cream",
        "Amul Kulfi 60ml", "Kwality Walls Magnum Ice Cream",
        "ITC Master Chef Frozen Veg Paratha 400g",
    ],
    "beauty-cosmetics": [
        "Lakme 9 to 5 Foundation 30ml", "Maybelline Fit Me Foundation 30ml",
        "Lakme Lipstick", "Maybelline Color Sensational Lipstick",
        "Maybelline Mascara 9ml", "Lakme Eyeconic Kajal",
        "Nykaa Nail Polish", "Colorbar Nail Polish",
        "Biotique Sunscreen SPF 50 120ml", "Lotus Herbals Sunscreen SPF 40 100ml",
        "Neutrogena Sunscreen SPF 50 88ml", "Lakme Sun Expert SPF 50 100ml",
        "Garnier Micellar Water 400ml", "Simple Micellar Water 200ml",
        "Olay Moisturizer 50g", "Pond's Age Miracle Cream 50g",
        "Lakme Kajal", "Maybelline Kajal", "Colorbar Kajal",
        "Lakme Eyeshadow Palette", "Maybelline Eyeshadow Palette",
        "Lakme Nail Color", "Maybelline Nail Color",
        "Garnier BB Cream 30ml", "Lakme CC Cream 30ml",
    ],
    "baby-care": [
        "Pampers Diapers Small 20 pcs", "Huggies Diapers Small 20 pcs", "Mamy Poko Diapers 20 pcs",
        "Nestle Cerelac Stage 1 300g", "Farex Baby Food 300g", "Heinz Baby Food 300g",
        "Johnson Baby Shampoo 200ml", "Johnson Baby Lotion 200ml", "Johnson Baby Powder 200g",
        "Himalaya Baby Cream 100g", "Himalaya Baby Shampoo 200ml",
        "Chicco Baby Wipes 72 pcs", "Pampers Baby Wipes 72 pcs",
        "Pampers Diapers Medium 20 pcs", "Huggies Diapers Medium 20 pcs",
        "Nestle Nan Pro 1 400g", "Similac Stage 1 400g",
        "Mamy Poko Pants Medium 20 pcs", "Huggies Wonder Pants Medium 20 pcs",
    ],
    "pet-care": [
        "Pedigree Adult Dog Food 1.2kg", "Royal Canin Dog Food 1kg", "Drools Dog Food 1.2kg",
        "Whiskas Cat Food 1.2kg", "Royal Canin Cat Food 1kg",
        "Trixie Dog Collar", "Ferplast Dog Leash", "Catit Cat Litter 5kg",
        "Pedigree Puppy Food 1.2kg", "Drools Puppy Food 1.2kg",
        "Whiskas Kitten Food 1.2kg", "Royal Canin Kitten Food 1kg",
        "Pedigree Dentastix Dog Treats 7 pcs", "Drools Dog Treats 100g",
    ],
    "electronics": [
        "boAt Bassheads 100 Earphones", "JBL C50HI Earphones", "Sony MDR-EX15AP Earphones",
        "Syska USB Cable 1m", "Portronics USB Cable 1m", "Anker USB Cable 1m",
        "Duracell AA Batteries 4 pcs", "Eveready AA Batteries 4 pcs",
        "Portronics Power Bank 10000mAh", "Mi Power Bank 10000mAh",
        "Syska LED Bulb 9W", "Philips LED Bulb 9W", "Havells LED Bulb 9W",
        "boAt Rockerz 255 Earphones", "JBL T110 Earphones",
        "Duracell AAA Batteries 4 pcs", "Eveready AAA Batteries 4 pcs",
        "Syska Type C Cable 1m", "Portronics Type C Cable 1m",
    ],
    "kitchen-essentials": [
        "Prestige Pressure Cooker 3L", "Hawkins Pressure Cooker 3L",
        "Tupperware Container Set", "Cello Container Set", "Milton Container Set",
        "Borosil Glass Set", "Cello Water Bottle 1L", "Milton Water Bottle 1L",
        "Pigeon Non Stick Tawa", "Prestige Non Stick Pan",
        "Scotch Brite Dish Cloth", "Vileda Mop",
        "Foil Paper 9m", "Cling Wrap 30m", "Zip Lock Bags 30 pcs",
        "Borosil Mixing Bowl Set", "Cello Mixing Bowl Set",
        "Prestige Induction Cooktop", "Pigeon Induction Cooktop",
        "Tupperware Water Bottle 1L", "Nayasa Water Bottle 1L",
    ],
}
