"""
Analytics API
=============
POST /analytics/event       — record a single user interaction event
POST /analytics/events/bulk — record multiple events in one request (batch)
GET  /analytics/stats       — admin: aggregated funnel & product stats
GET  /analytics/client/{client_id} — admin: full journey for one client
"""
import hashlib
import uuid
from datetime import datetime, timedelta, timezone
from typing import List, Optional

import structlog
from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, Field
from sqlalchemy import Integer, case, cast, desc, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.middleware.auth_middleware import get_current_user, get_optional_user
from app.models.analytics import UserEvent
from app.models.platform import Platform
from app.models.product import Product
from app.models.user import User

log = structlog.get_logger(__name__)
router = APIRouter()


# ═══════════════════════════════════════════════════════════════════════════
# Pydantic schemas
# ═══════════════════════════════════════════════════════════════════════════

class EventIn(BaseModel):
    """Payload the frontend sends for a single event."""

    event_type: str = Field(
        ...,
        pattern="^(product_view|cart_add|cart_remove|platform_redirect|search|checkout_start)$",
    )
    # Browser-persistent identity (generated once, stored in localStorage)
    client_id: str = Field(..., min_length=8, max_length=64)
    session_id: Optional[str] = Field(None, max_length=128)

    # What the user interacted with
    product_id: Optional[uuid.UUID] = None
    platform_id: Optional[uuid.UUID] = None

    # Event-specific payload
    price_shown: Optional[float] = None
    cart_item_count: Optional[int] = None
    search_query: Optional[str] = Field(None, max_length=500)
    referrer_page: Optional[str] = Field(None, max_length=100)
    redirect_url: Optional[str] = Field(None, max_length=2000)


class BulkEventsIn(BaseModel):
    events: List[EventIn] = Field(..., max_length=50)


class EventOut(BaseModel):
    id: uuid.UUID
    event_type: str
    client_id: str
    created_at: datetime

    model_config = {"from_attributes": True}


# ═══════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════

def _hash_ip(ip: str) -> str:
    """One-way hash of IP for privacy-safe storage."""
    return hashlib.sha256(ip.encode()).hexdigest()[:32]


def _client_ip(request: Request) -> str:
    forwarded = request.headers.get("X-Forwarded-For")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.client.host if request.client else "unknown"


async def _persist_event(
    db: AsyncSession,
    payload: EventIn,
    user: Optional[User],
    request: Request,
) -> UserEvent:
    ip = _client_ip(request)
    event = UserEvent(
        event_type=payload.event_type,
        user_id=user.id if user else None,
        client_id=payload.client_id,
        session_id=payload.session_id,
        product_id=payload.product_id,
        platform_id=payload.platform_id,
        price_shown=payload.price_shown,
        cart_item_count=payload.cart_item_count,
        search_query=payload.search_query,
        referrer_page=payload.referrer_page,
        redirect_url=payload.redirect_url,
        ip_hash=_hash_ip(ip),
    )
    db.add(event)
    await db.commit()
    await db.refresh(event)
    return event


# ═══════════════════════════════════════════════════════════════════════════
# Routes
# ═══════════════════════════════════════════════════════════════════════════

@router.post("/event", response_model=EventOut, status_code=status.HTTP_201_CREATED)
async def record_event(
    payload: EventIn,
    request: Request,
    db: AsyncSession = Depends(get_db),
    user: Optional[User] = Depends(get_optional_user),
):
    """
    Record a single user interaction event.
    Works for both authenticated users and anonymous visitors.
    The `client_id` must be a UUID generated by the browser and persisted
    in localStorage as `pb_client_id`.
    """
    event = await _persist_event(db, payload, user, request)
    log.info(
        "analytics.event_recorded",
        event_type=payload.event_type,
        client_id=payload.client_id,
        user_id=str(user.id) if user else None,
        product_id=str(payload.product_id) if payload.product_id else None,
    )
    return event


@router.post("/events/bulk", status_code=status.HTTP_201_CREATED)
async def record_events_bulk(
    payload: BulkEventsIn,
    request: Request,
    db: AsyncSession = Depends(get_db),
    user: Optional[User] = Depends(get_optional_user),
):
    """
    Record multiple events in one request (used for batching offline/queued events).
    Returns count of events saved.
    """
    saved = 0
    for ev in payload.events:
        ip = _client_ip(request)
        event = UserEvent(
            event_type=ev.event_type,
            user_id=user.id if user else None,
            client_id=ev.client_id,
            session_id=ev.session_id,
            product_id=ev.product_id,
            platform_id=ev.platform_id,
            price_shown=ev.price_shown,
            cart_item_count=ev.cart_item_count,
            search_query=ev.search_query,
            referrer_page=ev.referrer_page,
            redirect_url=ev.redirect_url,
            ip_hash=_hash_ip(ip),
        )
        db.add(event)
        saved += 1
    await db.commit()
    return {"saved": saved}


@router.get("/stats")
async def get_stats(
    days: int = 7,
    db: AsyncSession = Depends(get_db),
    admin: User = Depends(get_current_user),
):
    """
    Admin-only: aggregated analytics for the last N days.
    Returns:
      - event counts by type
      - top 10 most-viewed products
      - top 10 most-redirected products (platform clicks)
      - conversion funnel: views → cart_add → redirect
    """
    if not admin.is_admin:
        raise HTTPException(status_code=403, detail="Admin access required")

    since = datetime.now(timezone.utc) - timedelta(days=days)

    # ── Event counts by type ──────────────────────────────────────────────────
    counts_q = await db.execute(
        select(UserEvent.event_type, func.count().label("total"))
        .where(UserEvent.created_at >= since)
        .group_by(UserEvent.event_type)
    )
    event_counts = {row.event_type: row.total for row in counts_q}

    # ── Unique client IDs (total reach) ───────────────────────────────────────
    unique_clients_q = await db.execute(
        select(func.count(func.distinct(UserEvent.client_id)))
        .where(UserEvent.created_at >= since)
    )
    unique_clients = unique_clients_q.scalar_one()

    # ── Unique registered users ───────────────────────────────────────────────
    unique_users_q = await db.execute(
        select(func.count(func.distinct(UserEvent.user_id)))
        .where(UserEvent.created_at >= since, UserEvent.user_id.is_not(None))
    )
    unique_users = unique_users_q.scalar_one()

    # ── Top 10 viewed products ────────────────────────────────────────────────
    top_viewed_q = await db.execute(
        select(
            UserEvent.product_id,
            Product.name,
            Product.brand,
            func.count().label("views"),
        )
        .join(Product, Product.id == UserEvent.product_id)
        .where(
            UserEvent.event_type == "product_view",
            UserEvent.created_at >= since,
            UserEvent.product_id.is_not(None),
        )
        .group_by(UserEvent.product_id, Product.name, Product.brand)
        .order_by(desc("views"))
        .limit(10)
    )
    top_viewed = [
        {"product_id": str(r.product_id), "name": r.name, "brand": r.brand, "views": r.views}
        for r in top_viewed_q
    ]

    # ── Top 10 platform redirects (product + platform) ───────────────────────
    top_redirects_q = await db.execute(
        select(
            UserEvent.product_id,
            UserEvent.platform_id,
            Product.name,
            Platform.name.label("platform_name"),
            func.count().label("redirects"),
            func.avg(UserEvent.price_shown).label("avg_price"),
        )
        .join(Product, Product.id == UserEvent.product_id)
        .join(Platform, Platform.id == UserEvent.platform_id)
        .where(
            UserEvent.event_type == "platform_redirect",
            UserEvent.created_at >= since,
            UserEvent.product_id.is_not(None),
            UserEvent.platform_id.is_not(None),
        )
        .group_by(
            UserEvent.product_id, UserEvent.platform_id,
            Product.name, Platform.name,
        )
        .order_by(desc("redirects"))
        .limit(10)
    )
    top_redirects = [
        {
            "product_id": str(r.product_id),
            "platform_id": str(r.platform_id),
            "product_name": r.name,
            "platform_name": r.platform_name,
            "redirects": r.redirects,
            "avg_price": round(float(r.avg_price), 2) if r.avg_price else None,
        }
        for r in top_redirects_q
    ]

    # ── Top platforms by redirect count ──────────────────────────────────────
    platform_clicks_q = await db.execute(
        select(Platform.name, func.count().label("clicks"))
        .join(UserEvent, UserEvent.platform_id == Platform.id)
        .where(
            UserEvent.event_type == "platform_redirect",
            UserEvent.created_at >= since,
        )
        .group_by(Platform.name)
        .order_by(desc("clicks"))
    )
    platform_clicks = [
        {"platform": r.name, "clicks": r.clicks} for r in platform_clicks_q
    ]

    return {
        "period_days": days,
        "unique_clients": unique_clients,
        "unique_registered_users": unique_users,
        "event_counts": event_counts,
        "funnel": {
            "product_views": event_counts.get("product_view", 0),
            "cart_adds": event_counts.get("cart_add", 0),
            "platform_redirects": event_counts.get("platform_redirect", 0),
        },
        "top_viewed_products": top_viewed,
        "top_platform_redirects": top_redirects,
        "platform_clicks": platform_clicks,
    }


@router.get("/client/{client_id}")
async def get_client_journey(
    client_id: str,
    db: AsyncSession = Depends(get_db),
    admin: User = Depends(get_current_user),
):
    """
    Admin-only: full event history for a specific client_id.
    Shows the complete journey: search → view → add-to-cart → redirect.
    """
    if not admin.is_admin:
        raise HTTPException(status_code=403, detail="Admin access required")

    result = await db.execute(
        select(UserEvent)
        .where(UserEvent.client_id == client_id)
        .order_by(UserEvent.created_at.asc())
        .limit(500)
    )
    events = result.scalars().all()

    return {
        "client_id": client_id,
        "total_events": len(events),
        "events": [
            {
                "id": str(e.id),
                "event_type": e.event_type,
                "user_id": str(e.user_id) if e.user_id else None,
                "product_id": str(e.product_id) if e.product_id else None,
                "platform_id": str(e.platform_id) if e.platform_id else None,
                "price_shown": float(e.price_shown) if e.price_shown else None,
                "search_query": e.search_query,
                "referrer_page": e.referrer_page,
                "redirect_url": e.redirect_url,
                "created_at": e.created_at.isoformat(),
            }
            for e in events
        ],
    }
